services:

  test-database:
    container_name: weather.postgres.test
    image: postgres:16.4-alpine
    env_file:
      - .env.test
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data-test/postgres:/var/lib/postgresql/data
    networks:
      - test-network

  test-redis:
    container_name: weather.redis.test
    image: redis:latest
    env_file:
      - .env.test
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data-test/redis:/data
    networks:
      - test-network

  test-unit-frontend:
    container_name: weather.frontend.test
    build:
      context: frontend
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - test-network
    command: npm run test:unit

  test-unit-backend:
    container_name: weather.backend.test-unit
    build:
      context: backend
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - test-database
      - test-redis
    networks:
      - test-network
    command: npm run test:unit

  test-integration-backend:
    container_name: weather.backend.test-integration
    build:
      context: backend
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    volumes:
      - ./backend:/usr/src/app
      - ./backend/src/mail/templates:/usr/src/app/mail/templates
      - /usr/src/app/node_modules
    depends_on:
      - test-database
      - test-redis
    networks:
      - test-network
    command: npm run test:integration

  test-e2e-backend:
    container_name: weather.backend.test-e2e
    build:
      context: backend
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - test-database
      - test-redis
    networks:
      - test-network
    command: npm run test:e2e

networks:
  test-network:
    driver: bridge
