name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          echo "${{ secrets.ENV_TEST }}" > .env.test

      - name: Build and run unit tests
        run: docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit test-unit-backend test-unit-frontend

      - name: Build and run integration tests
        run: docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit test-integration-backend

      - name: Cleanup
        run: docker-compose -f docker-compose.test.yaml down -v