name: Integration Tests

on:
  push:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          cp .env.test.example .env.test
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_WEATHER_KEY }}" >> .env.test
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_SEARCH_KEY }}" >> .env.test
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env.test
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env.test

      - name: Run integration tests for backend
        run: docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit test-integration-backend

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yaml down -v